<template>
  <Layout class="info">
    <div class="relative flex flex-col w-full mx-auto xl:flex-row mx-auto" style="max-width: 1440px;"> 
        <div class="border border-indigo-900 w-full">
          Hello1
          <div class="xl:w-1/2 border border-blue-600">
          Hello2
            <div class="xl:fixed static border border-red-600" style="width:496px;">
              Hello3
            </div>
          </div>
        </div>

        <div class="xl:absolute static w-full xl:w-1/2 right-0 p-8">
            2 Fusce nisl arcu, rhoncus sit amet scelerisque quis, iaculis vel mi. Mauris non orci sit amet sem maximus vulputate. Nulla aliquet sapien ipsum, vitae lacinia est finibus eget. Maecenas at mi vitae eros feugiat interdum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse leo sem, hendrerit at elementum eu, pulvinar vel enim. Morbi id orci justo. Vestibulum commodo dui eu nibh sodales, nec tristique mi pulvinar. Vestibulum vel mauris elementum, pharetra tellus et, commodo erat. Sed sed augue augue. Mauris non auctor dolor. Vivamus egestas lectus neque, a commodo diam blandit at.

Fusce sit amet purus imperdiet, placerat dui quis, dignissim lacus. Praesent luctus et mauris sed gravida. Curabitur placerat mauris sed egestas volutpat. Aliquam ac velit scelerisque, consectetur nisl a, accumsan turpis. Quisque pretium nunc in massa fermentum accumsan. Curabitur fermentum lorem nulla, id auctor erat porta quis. Nulla dictum lacinia justo, ac ultricies nunc tristique eu. Mauris non lorem at nibh faucibus porta et ut lectus. Ut tempor erat nisl. Nulla odio leo, varius sit amet tristique id, cursus eget ipsum. Integer molestie magna elit. Fusce ac tellus in eros pharetra fermentum ac non libero.

Aenean pellentesque dui urna, et dignissim magna egestas et. Fusce diam enim, interdum at odio mollis, accumsan maximus mauris. Nulla facilisi. Nulla lobortis urna sed mi euismod, eu tristique est cursus. Curabitur quis ipsum scelerisque, suscipit diam et, feugiat felis. Pellentesque sit amet suscipit enim. Nam pharetra fringilla sem. Aenean commodo pulvinar dui tempus fringilla. Sed vulputate, dui sed facilisis mattis, metus sem aliquam velit, non aliquam neque risus quis diam. Morbi in interdum magna. Mauris iaculis eros at dui lacinia, in iaculis dui eleifend. Maecenas mollis hendrerit gravida.

Maecenas non ornare libero. Nunc venenatis suscipit mauris id lobortis. Pellentesque id ex aliquet, lobortis orci eu, ullamcorper erat. Pellentesque vel ante eu odio malesuada luctus. Ut ac est nec nunc hendrerit dapibus. Donec bibendum, ipsum a imperdiet hendrerit, ipsum arcu egestas odio, vitae mattis lacus libero vel ex. Mauris ac justo odio. Phasellus vehicula lacus dolor. Morbi euismod porttitor orci, vitae maximus sem viverra tempor. Vestibulum dapibus blandit tortor quis volutpat. Cras mattis mi sed urna volutpat ornare. Vestibulum pulvinar venenatis turpis eget porta. Donec condimentum quam vel sapien cursus dapibus. Nullam scelerisque, elit sed mollis vehicula, arcu risus tristique lacus, in vestibulum augue leo viverra odio. Donec fringilla odio et ante dapibus, in porta arcu rutrum. Vivamus ipsum ex, lacinia sit amet purus quis, dapibus vestibulum urna.
        Fusce nisl arcu, rhoncus sit amet scelerisque quis, iaculis vel mi. Mauris non orci sit amet sem maximus vulputate. Nulla aliquet sapien ipsum, vitae lacinia est finibus eget. Maecenas at mi vitae eros feugiat interdum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse leo sem, hendrerit at elementum eu, pulvinar vel enim. Morbi id orci justo. Vestibulum commodo dui eu nibh sodales, nec tristique mi pulvinar. Vestibulum vel mauris elementum, pharetra tellus et, commodo erat. Sed sed augue augue. Mauris non auctor dolor. Vivamus egestas lectus neque, a commodo diam blandit at.

Fusce sit amet purus imperdiet, placerat dui quis, dignissim lacus. Praesent luctus et mauris sed gravida. Curabitur placerat mauris sed egestas volutpat. Aliquam ac velit scelerisque, consectetur nisl a, accumsan turpis. Quisque pretium nunc in massa fermentum accumsan. Curabitur fermentum lorem nulla, id auctor erat porta quis. Nulla dictum lacinia justo, ac ultricies nunc tristique eu. Mauris non lorem at nibh faucibus porta et ut lectus. Ut tempor erat nisl. Nulla odio leo, varius sit amet tristique id, cursus eget ipsum. Integer molestie magna elit. Fusce ac tellus in eros pharetra fermentum ac non libero.

Aenean pellentesque dui urna, et dignissim magna egestas et. Fusce diam enim, interdum at odio mollis, accumsan maximus mauris. Nulla facilisi. Nulla lobortis urna sed mi euismod, eu tristique est cursus. Curabitur quis ipsum scelerisque, suscipit diam et, feugiat felis. Pellentesque sit amet suscipit enim. Nam pharetra fringilla sem. Aenean commodo pulvinar dui tempus fringilla. Sed vulputate, dui sed facilisis mattis, metus sem aliquam velit, non aliquam neque risus quis diam. Morbi in interdum magna. Mauris iaculis eros at dui lacinia, in iaculis dui eleifend. Maecenas mollis hendrerit gravida.

Maecenas non ornare libero. Nunc venenatis suscipit mauris id lobortis. Pellentesque id ex aliquet, lobortis orci eu, ullamcorper erat. Pellentesque vel ante eu odio malesuada luctus. Ut ac est nec nunc hendrerit dapibus. Donec bibendum, ipsum a imperdiet hendrerit, ipsum arcu egestas odio, vitae mattis lacus libero vel ex. Mauris ac justo odio. Phasellus vehicula lacus dolor. Morbi euismod porttitor orci, vitae maximus sem viverra tempor. Vestibulum dapibus blandit tortor quis volutpat. Cras mattis mi sed urna volutpat ornare. Vestibulum pulvinar venenatis turpis eget porta. Donec condimentum quam vel sapien cursus dapibus. Nullam scelerisque, elit sed mollis vehicula, arcu risus tristique lacus, in vestibulum augue leo viverra odio. Donec fringilla odio et ante dapibus, in porta arcu rutrum. Vivamus ipsum ex, lacinia sit amet purus quis, dapibus vestibulum urna.
Fusce nisl arcu, rhoncus sit amet scelerisque quis, iaculis vel mi. Mauris non orci sit amet sem maximus vulputate. Nulla aliquet sapien ipsum, vitae lacinia est finibus eget. Maecenas at mi vitae eros feugiat interdum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse leo sem, hendrerit at elementum eu, pulvinar vel enim. Morbi id orci justo. Vestibulum commodo dui eu nibh sodales, nec tristique mi pulvinar. Vestibulum vel mauris elementum, pharetra tellus et, commodo erat. Sed sed augue augue. Mauris non auctor dolor. Vivamus egestas lectus neque, a commodo diam blandit at.

Fusce sit amet purus imperdiet, placerat dui quis, dignissim lacus. Praesent luctus et mauris sed gravida. Curabitur placerat mauris sed egestas volutpat. Aliquam ac velit scelerisque, consectetur nisl a, accumsan turpis. Quisque pretium nunc in massa fermentum accumsan. Curabitur fermentum lorem nulla, id auctor erat porta quis. Nulla dictum lacinia justo, ac ultricies nunc tristique eu. Mauris non lorem at nibh faucibus porta et ut lectus. Ut tempor erat nisl. Nulla odio leo, varius sit amet tristique id, cursus eget ipsum. Integer molestie magna elit. Fusce ac tellus in eros pharetra fermentum ac non libero.

Aenean pellentesque dui urna, et dignissim magna egestas et. Fusce diam enim, interdum at odio mollis, accumsan maximus mauris. Nulla facilisi. Nulla lobortis urna sed mi euismod, eu tristique est cursus. Curabitur quis ipsum scelerisque, suscipit diam et, feugiat felis. Pellentesque sit amet suscipit enim. Nam pharetra fringilla sem. Aenean commodo pulvinar dui tempus fringilla. Sed vulputate, dui sed facilisis mattis, metus sem aliquam velit, non aliquam neque risus quis diam. Morbi in interdum magna. Mauris iaculis eros at dui lacinia, in iaculis dui eleifend. Maecenas mollis hendrerit gravida.

Maecenas non ornare libero. Nunc venenatis suscipit mauris id lobortis. Pellentesque id ex aliquet, lobortis orci eu, ullamcorper erat. Pellentesque vel ante eu odio malesuada luctus. Ut ac est nec nunc hendrerit dapibus. Donec bibendum, ipsum a imperdiet hendrerit, ipsum arcu egestas odio, vitae mattis lacus libero vel ex. Mauris ac justo odio. Phasellus vehicula lacus dolor. Morbi euismod porttitor orci, vitae maximus sem viverra tempor. Vestibulum dapibus blandit tortor quis volutpat. Cras mattis mi sed urna volutpat ornare. Vestibulum pulvinar venenatis turpis eget porta. Donec condimentum quam vel sapien cursus dapibus. Nullam scelerisque, elit sed mollis vehicula, arcu risus tristique lacus, in vestibulum augue leo viverra odio. Donec fringilla odio et ante dapibus, in porta arcu rutrum. Vivamus ipsum ex, lacinia sit amet purus quis, dapibus vestibulum urna.
Fusce nisl arcu, rhoncus sit amet scelerisque quis, iaculis vel mi. Mauris non orci sit amet sem maximus vulputate. Nulla aliquet sapien ipsum, vitae lacinia est finibus eget. Maecenas at mi vitae eros feugiat interdum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse leo sem, hendrerit at elementum eu, pulvinar vel enim. Morbi id orci justo. Vestibulum commodo dui eu nibh sodales, nec tristique mi pulvinar. Vestibulum vel mauris elementum, pharetra tellus et, commodo erat. Sed sed augue augue. Mauris non auctor dolor. Vivamus egestas lectus neque, a commodo diam blandit at.

Fusce sit amet purus imperdiet, placerat dui quis, dignissim lacus. Praesent luctus et mauris sed gravida. Curabitur placerat mauris sed egestas volutpat. Aliquam ac velit scelerisque, consectetur nisl a, accumsan turpis. Quisque pretium nunc in massa fermentum accumsan. Curabitur fermentum lorem nulla, id auctor erat porta quis. Nulla dictum lacinia justo, ac ultricies nunc tristique eu. Mauris non lorem at nibh faucibus porta et ut lectus. Ut tempor erat nisl. Nulla odio leo, varius sit amet tristique id, cursus eget ipsum. Integer molestie magna elit. Fusce ac tellus in eros pharetra fermentum ac non libero.

Aenean pellentesque dui urna, et dignissim magna egestas et. Fusce diam enim, interdum at odio mollis, accumsan maximus mauris. Nulla facilisi. Nulla lobortis urna sed mi euismod, eu tristique est cursus. Curabitur quis ipsum scelerisque, suscipit diam et, feugiat felis. Pellentesque sit amet suscipit enim. Nam pharetra fringilla sem. Aenean commodo pulvinar dui tempus fringilla. Sed vulputate, dui sed facilisis mattis, metus sem aliquam velit, non aliquam neque risus quis diam. Morbi in interdum magna. Mauris iaculis eros at dui lacinia, in iaculis dui eleifend. Maecenas mollis hendrerit gravida.

Maecenas non ornare libero. Nunc venenatis suscipit mauris id lobortis. Pellentesque id ex aliquet, lobortis orci eu, ullamcorper erat. Pellentesque vel ante eu odio malesuada luctus. Ut ac est nec nunc hendrerit dapibus. Donec bibendum, ipsum a imperdiet hendrerit, ipsum arcu egestas odio, vitae mattis lacus libero vel ex. Mauris ac justo odio. Phasellus vehicula lacus dolor. Morbi euismod porttitor orci, vitae maximus sem viverra tempor. Vestibulum dapibus blandit tortor quis volutpat. Cras mattis mi sed urna volutpat ornare. Vestibulum pulvinar venenatis turpis eget porta. Donec condimentum quam vel sapien cursus dapibus. Nullam scelerisque, elit sed mollis vehicula, arcu risus tristique lacus, in vestibulum augue leo viverra odio. Donec fringilla odio et ante dapibus, in porta arcu rutrum. Vivamus ipsum ex, lacinia sit amet purus quis, dapibus vestibulum urna.
Fusce nisl arcu, rhoncus sit amet scelerisque quis, iaculis vel mi. Mauris non orci sit amet sem maximus vulputate. Nulla aliquet sapien ipsum, vitae lacinia est finibus eget. Maecenas at mi vitae eros feugiat interdum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse leo sem, hendrerit at elementum eu, pulvinar vel enim. Morbi id orci justo. Vestibulum commodo dui eu nibh sodales, nec tristique mi pulvinar. Vestibulum vel mauris elementum, pharetra tellus et, commodo erat. Sed sed augue augue. Mauris non auctor dolor. Vivamus egestas lectus neque, a commodo diam blandit at.

Fusce sit amet purus imperdiet, placerat dui quis, dignissim lacus. Praesent luctus et mauris sed gravida. Curabitur placerat mauris sed egestas volutpat. Aliquam ac velit scelerisque, consectetur nisl a, accumsan turpis. Quisque pretium nunc in massa fermentum accumsan. Curabitur fermentum lorem nulla, id auctor erat porta quis. Nulla dictum lacinia justo, ac ultricies nunc tristique eu. Mauris non lorem at nibh faucibus porta et ut lectus. Ut tempor erat nisl. Nulla odio leo, varius sit amet tristique id, cursus eget ipsum. Integer molestie magna elit. Fusce ac tellus in eros pharetra fermentum ac non libero.

Aenean pellentesque dui urna, et dignissim magna egestas et. Fusce diam enim, interdum at odio mollis, accumsan maximus mauris. Nulla facilisi. Nulla lobortis urna sed mi euismod, eu tristique est cursus. Curabitur quis ipsum scelerisque, suscipit diam et, feugiat felis. Pellentesque sit amet suscipit enim. Nam pharetra fringilla sem. Aenean commodo pulvinar dui tempus fringilla. Sed vulputate, dui sed facilisis mattis, metus sem aliquam velit, non aliquam neque risus quis diam. Morbi in interdum magna. Mauris iaculis eros at dui lacinia, in iaculis dui eleifend. Maecenas mollis hendrerit gravida.

Maecenas non ornare libero. Nunc venenatis suscipit mauris id lobortis. Pellentesque id ex aliquet, lobortis orci eu, ullamcorper erat. Pellentesque vel ante eu odio malesuada luctus. Ut ac est nec nunc hendrerit dapibus. Donec bibendum, ipsum a imperdiet hendrerit, ipsum arcu egestas odio, vitae mattis lacus libero vel ex. Mauris ac justo odio. Phasellus vehicula lacus dolor. Morbi euismod porttitor orci, vitae maximus sem viverra tempor. Vestibulum dapibus blandit tortor quis volutpat. Cras mattis mi sed urna volutpat ornare. Vestibulum pulvinar venenatis turpis eget porta. Donec condimentum quam vel sapien cursus dapibus. Nullam scelerisque, elit sed mollis vehicula, arcu risus tristique lacus, in vestibulum augue leo viverra odio. Donec fringilla odio et ante dapibus, in porta arcu rutrum. Vivamus ipsum ex, lacinia sit amet purus quis, dapibus vestibulum urna.
Fusce nisl arcu, rhoncus sit amet scelerisque quis, iaculis vel mi. Mauris non orci sit amet sem maximus vulputate. Nulla aliquet sapien ipsum, vitae lacinia est finibus eget. Maecenas at mi vitae eros feugiat interdum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse leo sem, hendrerit at elementum eu, pulvinar vel enim. Morbi id orci justo. Vestibulum commodo dui eu nibh sodales, nec tristique mi pulvinar. Vestibulum vel mauris elementum, pharetra tellus et, commodo erat. Sed sed augue augue. Mauris non auctor dolor. Vivamus egestas lectus neque, a commodo diam blandit at.

Fusce sit amet purus imperdiet, placerat dui quis, dignissim lacus. Praesent luctus et mauris sed gravida. Curabitur placerat mauris sed egestas volutpat. Aliquam ac velit scelerisque, consectetur nisl a, accumsan turpis. Quisque pretium nunc in massa fermentum accumsan. Curabitur fermentum lorem nulla, id auctor erat porta quis. Nulla dictum lacinia justo, ac ultricies nunc tristique eu. Mauris non lorem at nibh faucibus porta et ut lectus. Ut tempor erat nisl. Nulla odio leo, varius sit amet tristique id, cursus eget ipsum. Integer molestie magna elit. Fusce ac tellus in eros pharetra fermentum ac non libero.

Aenean pellentesque dui urna, et dignissim magna egestas et. Fusce diam enim, interdum at odio mollis, accumsan maximus mauris. Nulla facilisi. Nulla lobortis urna sed mi euismod, eu tristique est cursus. Curabitur quis ipsum scelerisque, suscipit diam et, feugiat felis. Pellentesque sit amet suscipit enim. Nam pharetra fringilla sem. Aenean commodo pulvinar dui tempus fringilla. Sed vulputate, dui sed facilisis mattis, metus sem aliquam velit, non aliquam neque risus quis diam. Morbi in interdum magna. Mauris iaculis eros at dui lacinia, in iaculis dui eleifend. Maecenas mollis hendrerit gravida.

Maecenas non ornare libero. Nunc venenatis suscipit mauris id lobortis. Pellentesque id ex aliquet, lobortis orci eu, ullamcorper erat. Pellentesque vel ante eu odio malesuada luctus. Ut ac est nec nunc hendrerit dapibus. Donec bibendum, ipsum a imperdiet hendrerit, ipsum arcu egestas odio, vitae mattis lacus libero vel ex. Mauris ac justo odio. Phasellus vehicula lacus dolor. Morbi euismod porttitor orci, vitae maximus sem viverra tempor. Vestibulum dapibus blandit tortor quis volutpat. Cras mattis mi sed urna volutpat ornare. Vestibulum pulvinar venenatis turpis eget porta. Donec condimentum quam vel sapien cursus dapibus. Nullam scelerisque, elit sed mollis vehicula, arcu risus tristique lacus, in vestibulum augue leo viverra odio. Donec fringilla odio et ante dapibus, in porta arcu rutrum. Vivamus ipsum ex, lacinia sit amet purus quis, dapibus vestibulum urna.
        </div>
    </div>
  </Layout>
</template>

<script>
export default {
  metaInfo: {
    title: ''
  }
}
</script>
